# Generated by Django 4.2.7 on 2025-09-21 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование корпуса')),
                ('address', models.TextField(verbose_name='Адрес корпуса')),
                ('floors_count', models.PositiveIntegerField(verbose_name='Количество этажей')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Корпус',
                'verbose_name_plural': 'Корпуса',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название подразделения')),
                ('department_type', models.CharField(choices=[('university', 'Университет'), ('faculty', 'Факультет'), ('department', 'Кафедра'), ('laboratory', 'Лаборатория'), ('center', 'Центр'), ('institute', 'Институт')], max_length=50, verbose_name='Тип подразделения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auditorium_app.department', verbose_name='Родительское подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='Номер комнаты')),
                ('floor', models.PositiveIntegerField(verbose_name='Этаж')),
                ('location_in_building', models.CharField(max_length=200, verbose_name='Расположение в корпусе')),
                ('width', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ширина (м)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Длина (м)')),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота потолков (м)')),
                ('purpose', models.CharField(choices=[('lecture', 'Лекционная аудитория'), ('seminar', 'Семинарская аудитория'), ('laboratory', 'Лаборатория'), ('office', 'Кабинет'), ('library', 'Библиотека'), ('conference', 'Конференц-зал'), ('computer', 'Компьютерный класс'), ('storage', 'Складское помещение'), ('utility', 'Вспомогательное помещение'), ('recreation', 'Комната отдыха')], max_length=50, verbose_name='Назначение')),
                ('room_type', models.CharField(choices=[('auditorium', 'Аудитория'), ('office', 'Офис'), ('laboratory', 'Лаборатория'), ('storage', 'Склад'), ('utility', 'Вспомогательное'), ('recreation', 'Отдых')], max_length=50, verbose_name='Вид помещения')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='auditorium_app.building', verbose_name='Корпус')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorium_app.department', verbose_name='Закрепленное подразделение')),
            ],
            options={
                'verbose_name': 'Помещение',
                'verbose_name_plural': 'Помещения',
                'ordering': ['building', 'floor', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='BuildingFloor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_number', models.IntegerField(verbose_name='Номер этажа')),
                ('ceiling_height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Высота потолков (м)')),
                ('description', models.TextField(blank=True, verbose_name='Описание этажа')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='auditorium_app.building', verbose_name='Корпус')),
            ],
            options={
                'verbose_name': 'Этаж корпуса',
                'verbose_name_plural': 'Этажи корпусов',
                'ordering': ['building', 'floor_number'],
                'unique_together': {('building', 'floor_number')},
            },
        ),
    ]
